# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3689b6e841791267d057010b1606fadf6d9860ba070fc56b0a73d0f8de4fac796d9fdd8d2c4266c0447e3eea416198e9f2bb4e16530301b0d035d61d1449f0cb

test:
  secret_key_base: 5ee85ba7dffbdab35b5b72a41d158ea5e3c6549d456cebb1a27659d8de1720fc688b7582f248d2964bcae3132847e25cc4fc67764abe695e0f9acd326e10e5cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
